# permissions for end users to edit persistentvolumeclaiminstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistentvolumeclaiminstance-editor-role
rules:
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - persistentvolumeclaiminstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - persistentvolumeclaiminstances/status
  verbs:
  - get
