---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - jobexecutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - jobexecutions/finalizers
  verbs:
  - update
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - jobexecutions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dispatcher.ivan.vc
  resources:
  - jobtemplates
  verbs:
  - get
  - list
  - watch
