apiVersion: dispatcher.ivan.vc/v1alpha1
kind: JobTemplate
metadata:
  name: jobtemplate-sample
spec:
  jobTemplate:
    metadata:
      labels:
        test-label: test
    spec:
      template:
        metadata:
          labels:
            pod-label: test
        spec:
          containers:
          - name: pi
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            env:
            - name: PAYLOAD
              value: "{{ .Payload }}"
            - name: Date
              value: "{{.Date}}"
          restartPolicy: Never
      backoffLimit: 4
